### ISSUE TITLE
Error caught in "playerStage.submit" callback

### ISSUE THREAD

**Issue by joaomlopes** [empiricaly/empirica#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a stage ended, if a selection happens within the remainder 5/10 seconds, the error shows up, and the game stops and shows a loading animation.

### Steps To Reproduce

1. Run a batch (we tried with 4 and 6 players).
2. Select an option when there's only 5 to 10 seconds left
3. The error should happen.

### Empirica Version

```text
Version: v1.0.0
SHA:     d768c7c
Build:   173
Branch:  main
Time:    2023-01-01T12:53:01Z
```

### What OS are you seeing the problem on?

Linux

### What browser are you seeing the problem on?

Firefox, Chrome, Safari

### Relevant log output

```shell
[server] 17:01:04.996 ERR Error caught in "playerStage.submit" callback:
[server] 17:01:05.206 ERR TypeError: Cannot read properties of undefined (reading 'get')
[server] 17:01:05.206 ERR   at <anonymous> (/app/server/node_modules/@empirica/core/src/admin/classic/classic.ts:618:71)
[server] 17:01:05.207 ERR   at Array.every (<anonymous>)
[server] 17:01:05.207 ERR   at Object.callback (/app/server/node_modules/@empirica/core/src/admin/classic/classic.ts:618:49)
[server] 17:01:05.207 ERR   at Object.next (/app/server/node_modules/@empirica/core/src/admin/cake.ts:309:30)
[server] 17:01:05.208 ERR   at e.e.next (/app/server/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
[server] 17:01:05.208 ERR   at t.t._next (/app/server/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
[server] 17:01:05.209 ERR   at t.t.next (/app/server/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
[server] 17:01:05.209 ERR   at <anonymous> (/app/server/node_modules/rxjs/src/internal/Subject.ts:68:20)
[server] 17:01:05.209 ERR   at Object.Wq (/app/server/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
[server] 17:01:05.210 ERR   at t.t.next (/app/server/node_modules/rxjs/src/internal/Subject.ts:61:5)
```

### Anything else?

![Screenshot 2023-04-28 at 19 33 21](https://user-images.githubusercontent.com/5059164/235226409-8a46b503-c1b0-4167-8d8f-23051e709605.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
I was not able to reproduce this issue. It looks like you are running an older version of Empirica (1.0.0). Could you try and update your Empirica version to the latest using `empirica upgrade` at the root of your project and see if that improves the situation. I am not sure what else in your project might be triggering your problem. If you're still seeing the issue after you update, if you don't mind sharing your project with me, I'd be glad to take a look at it.

**Comment by npaton** [comment]
I've also pushed a fix in the latest release that might catch the error if it happens again. 👍

**Comment by joaomlopes** [comment]
Hey @npaton, when I try to run `empirica upgrade` I get this error
```
empirica upgrade
✓  Upgrade empirica packages
Error downloading: https://install.empirica.dev/empirica/darwin/arm64/version/v/empirica
23:46:30.995 FTL empirica: failed to start error="upgrade command: download binary: http fetch: server returned 404 Not Found"
```

Any tip?

**Comment by npaton** [comment]
I think there might have been an issue with upgrading with `v1.0.0`.
Can you try to upgrade manually by following these steps:
- upgrade the `empirica` command: edit the file called `.empirica/release`, on the "version:" line, set the value to `v1.3.1`
- upgrade client: 
    ```
    cd client
    npm install @empirica/core@latest
    ```
- upgrade server:
    ```
    cd server
    npm install @empirica/core@latest
    ```

**Comment by joaomlopes** [comment]
Hi @npaton. Thanks, I've updated and the issue persists.

There's no error this time though, the experiment just fails and the loading shows up. We have to manually stop the batch and start a new one.

The only thing I was able to extract is the last message received by the /query
```
{"payload":{"data":{"changes":{"done":true,"removed":false,"change":{"__typename":"AttributeChange","id":"01GZXZ6FKJN3HP1CPA8RE8MP3V","nodeID":"01GZXZ6F5F0CWWCPF6CK1ZDYNB","deleted":false,"createdAt":"2023-05-08T15:20:35.186843861Z","isNew":false,"index":null,"vector":false,"version":2,"key":"ran-after-01GZXZ6F6JV8TKB0T2PYMSQYHJ","val":"true"}}},"extensions":{"tracing":{"version":1,"startTime":"2023-05-08T15:18:06.361973846Z","endTime":"2023-05-08T15:20:35.193676767Z","duration":148831702875,"parsing":{"startOffset":41927,"duration":37088},"validation":{"startOffset":79112,"duration":110497},"execution":{"resolvers":[{"path":["done"],"parentType":"ChangePayload","fieldName":"done","returnType":"Boolean!","startOffset":148831661600,"duration":230},{"path":["removed"],"parentType":"ChangePayload","fieldName":"removed","returnType":"Boolean","startOffset":148831670695,"duration":329},{"path":["change"],"parentType":"ChangePayload","fieldName":"change","returnType":"Change","startOffset":148831673016,"duration":127},{"path":["change","id"],"parentType":"AttributeChange","fieldName":"id","returnType":"ID!","startOffset":148831678264,"duration":199},{"path":["change","nodeID"],"parentType":"AttributeChange","fieldName":"nodeID","returnType":"ID!","startOffset":148831680122,"duration":251},{"path":["change","deleted"],"parentType":"AttributeChange","fieldName":"deleted","returnType":"Boolean!","startOffset":148831682092,"duration":103},{"path":["change","isNew"],"parentType":"AttributeChange","fieldName":"isNew","returnType":"Boolean!","startOffset":148831684120,"duration":136},{"path":["change","index"],"parentType":"AttributeChange","fieldName":"index","returnType":"Int","startOffset":148831685659,"duration":124},{"path":["change","vector"],"parentType":"AttributeChange","fieldName":"vector","returnType":"Boolean!","startOffset":148831687240,"duration":107},{"path":["change","version"],"parentType":"AttributeChange","fieldName":"version","returnType":"Int!","startOffset":148831689272,"duration":166},{"path":["change","key"],"parentType":"AttributeChange","fieldName":"key","returnType":"String!","startOffset":148831690776,"duration":178},{"path":["change","val"],"parentType":"AttributeChange","fieldName":"val","returnType":"String","startOffset":148831692482,"duration":109},{"path":["change","createdAt"],"parentType":"AttributeChange","fieldName":"createdAt","returnType":"DateTime!","startOffset":148831694021,"duration":297}]}}}},"id":"5a2e0d03-0527-4c11-837c-7f631c7a2e30","type":"next"}
```

Does this help?

**Comment by joaomlopes** [comment]
Hi @npaton. Just wanted to ping and see if my comment above helps. 

I discussed this with the team and if you still want to check our code as you suggested above, just let us know how can we give you access to the repository.
